/**
 * Audio tracks (files live in /public). Set to null to disable.
 *  - music: generated by `npm run soundtrack` (original, royalty-free synthesis),
 *           or replace with a licensed track of your choice.
 *  - voiceover: drop a narrated WAV/MP3 here once recorded (script: COPY.narration).
 */
export const AUDIO = {
  music: "audio/soundtrack.wav" as string | null,
  musicVolume: 0.9,
  voiceover: null as string | null,
  voiceoverVolume: 1,
  /** Music level while voiceover plays (ducking). */
  musicVolumeUnderVoice: 0.35,
};
